// vocab/en_b2_p1.js
// B2 Phase 1 - Praepositionen & Praezise Verben (55 Woerter)
window.VOCAB_B2_P1 = [
{id:"b2_001",de:"bestehen auf",target:"to insist on",lv:"B2",tp:"Praep",ty:"verb",example_de:"Er besteht auf einer Erklaerung.",example_target:"He insists on an explanation.",mod:"m1"},
{id:"b2_002",de:"sich einigen auf",target:"to agree on",lv:"B2",tp:"Praep",ty:"verb",example_de:"Wir einigten uns auf einen Termin.",example_target:"We agreed on a date.",mod:"m1"},
{id:"b2_003",de:"abhaengen von",target:"to depend on",lv:"B2",tp:"Praep",ty:"verb",example_de:"Das haengt von dir ab.",example_target:"That depends on you.",mod:"m1"},
{id:"b2_004",de:"bestehen aus",target:"to consist of",lv:"B2",tp:"Praep",ty:"verb",example_de:"Das Team besteht aus fuenf Personen.",example_target:"The team consists of five people.",mod:"m1"},
{id:"b2_005",de:"hinweisen auf",target:"to point out",lv:"B2",tp:"Praep",ty:"verb",example_de:"Er wies auf den Fehler hin.",example_target:"He pointed out the mistake.",mod:"m1"},
{id:"b2_006",de:"sich kuemmern um",target:"to look after",lv:"B2",tp:"Praep",ty:"verb",example_de:"Sie kuemmert sich um die Kinder.",example_target:"She looks after the children.",mod:"m1"},
{id:"b2_007",de:"sich bewerben um",target:"to apply for",lv:"B2",tp:"Praep",ty:"verb",example_de:"Er bewirbt sich um die Stelle.",example_target:"He is applying for the position.",mod:"m1"},
{id:"b2_008",de:"verzichten auf",target:"to give up / do without",lv:"B2",tp:"Praep",ty:"verb",example_de:"Sie verzichtet auf Zucker.",example_target:"She does without sugar.",mod:"m1"},
{id:"b2_009",de:"ankommen auf",target:"to come down to",lv:"B2",tp:"Praep",ty:"verb",example_de:"Es kommt darauf an.",example_target:"It comes down to that.",mod:"m1"},
{id:"b2_010",de:"eingehen auf",target:"to respond to",lv:"B2",tp:"Praep",ty:"verb",example_de:"Er geht nicht auf die Frage ein.",example_target:"He doesn't respond to the question.",mod:"m1"},
{id:"b2_011",de:"sich verlassen auf",target:"to count on",lv:"B2",tp:"Praep",ty:"verb",example_de:"Du kannst auf mich zaehlen.",example_target:"You can count on me.",mod:"m1"},
{id:"b2_012",de:"im Voraus",target:"in advance",lv:"B2",tp:"Praep",ty:"adv",example_de:"Bitte bezahlen Sie im Voraus.",example_target:"Please pay in advance.",mod:"m1"},
{id:"b2_013",de:"angesichts",target:"in view of / given",lv:"B2",tp:"Praep",ty:"adv",example_de:"Angesichts der Lage ist das verstaendlich.",example_target:"Given the situation, that is understandable.",mod:"m1"},
{id:"b2_014",de:"im Gegensatz zu",target:"in contrast to",lv:"B2",tp:"Praep",ty:"adv",example_de:"Im Gegensatz zu ihm bin ich ruhig.",example_target:"In contrast to him, I am calm.",mod:"m1"},
{id:"b2_015",de:"trotz",target:"despite",lv:"B2",tp:"Praep",ty:"adv",example_de:"Trotz des Regens gingen wir spazieren.",example_target:"Despite the rain, we went for a walk.",mod:"m1"},
{id:"b2_016",de:"aufgrund von",target:"due to",lv:"B2",tp:"Praep",ty:"adv",example_de:"Aufgrund des Staus kamen wir zu spaet.",example_target:"Due to the traffic jam, we were late.",mod:"m1"},
{id:"b2_017",de:"im Hinblick auf",target:"with regard to",lv:"B2",tp:"Praep",ty:"adv",example_de:"Im Hinblick auf die Kosten ist das guenstig.",example_target:"With regard to costs, that is reasonable.",mod:"m1"},
{id:"b2_018",de:"abgesehen von",target:"apart from",lv:"B2",tp:"Praep",ty:"adv",example_de:"Abgesehen davon hat er recht.",example_target:"Apart from that, he is right.",mod:"m1"},
{id:"b2_019",de:"anstatt",target:"instead of",lv:"B2",tp:"Praep",ty:"adv",example_de:"Anstatt zu klagen, handle.",example_target:"Instead of complaining, act.",mod:"m1"},
{id:"b2_020",de:"im Zusammenhang mit",target:"in connection with",lv:"B2",tp:"Praep",ty:"adv",example_de:"Im Zusammenhang mit dem Projekt.",example_target:"In connection with the project.",mod:"m1"},
{id:"b2_021",de:"abwaegen",target:"to weigh up",lv:"B2",tp:"Verben",ty:"verb",example_de:"Ich muss die Optionen abwaegen.",example_target:"I need to weigh up the options.",mod:"m1"},
{id:"b2_022",de:"verdeutlichen",target:"to clarify",lv:"B2",tp:"Verben",ty:"verb",example_de:"Koennen Sie das verdeutlichen?",example_target:"Could you clarify that?",mod:"m1"},
{id:"b2_023",de:"rechtfertigen",target:"to justify",lv:"B2",tp:"Verben",ty:"verb",example_de:"Wie rechtfertigst du das?",example_target:"How do you justify that?",mod:"m1"},
{id:"b2_024",de:"widersprechen",target:"to contradict",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das widerspricht sich.",example_target:"That contradicts itself.",mod:"m1"},
{id:"b2_025",de:"beruecksichtigen",target:"to take into account",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das sollte beruecksichtigt werden.",example_target:"That should be taken into account.",mod:"m1"},
{id:"b2_026",de:"voraussetzen",target:"to presuppose",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das setzt Erfahrung voraus.",example_target:"That presupposes experience.",mod:"m1"},
{id:"b2_027",de:"aufwerfen",target:"to raise a question",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das wirft Fragen auf.",example_target:"That raises questions.",mod:"m1"},
{id:"b2_028",de:"in Frage stellen",target:"to question",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das sollte man in Frage stellen.",example_target:"That should be questioned.",mod:"m1"},
{id:"b2_029",de:"nachgeben",target:"to give in",lv:"B2",tp:"Verben",ty:"verb",example_de:"Sie gab schliesslich nach.",example_target:"She finally gave in.",mod:"m1"},
{id:"b2_030",de:"uebertreffen",target:"to exceed",lv:"B2",tp:"Verben",ty:"verb",example_de:"Die Ergebnisse uebertrafen unsere Erwartungen.",example_target:"The results exceeded our expectations.",mod:"m1"},
{id:"b2_031",de:"einschraenken",target:"to restrict",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das schraenkt uns ein.",example_target:"That restricts us.",mod:"m1"},
{id:"b2_032",de:"umgehen mit",target:"to deal with",lv:"B2",tp:"Verben",ty:"verb",example_de:"Wie gehst du damit um?",example_target:"How do you deal with that?",mod:"m1"},
{id:"b2_033",de:"hervorrufen",target:"to trigger",lv:"B2",tp:"Verben",ty:"verb",example_de:"Was hat das hervorgerufen?",example_target:"What triggered that?",mod:"m1"},
{id:"b2_034",de:"veranschaulichen",target:"to illustrate",lv:"B2",tp:"Verben",ty:"verb",example_de:"Lassen Sie mich das veranschaulichen.",example_target:"Let me illustrate that.",mod:"m1"},
{id:"b2_035",de:"bekraeftigen",target:"to reinforce",lv:"B2",tp:"Verben",ty:"verb",example_de:"Das bekraeftigt meine These.",example_target:"That reinforces my argument.",mod:"m1"},
{id:"b2_036",de:"die Schlussfolgerung",target:"the conclusion",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Was ist deine Schlussfolgerung?",example_target:"What is your conclusion?",mod:"m1"},
{id:"b2_037",de:"die Voraussetzung",target:"the prerequisite",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Das ist eine Grundvoraussetzung.",example_target:"That is a basic prerequisite.",mod:"m1"},
{id:"b2_038",de:"die Einschraenkung",target:"the limitation",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Das hat seine Einschraenkungen.",example_target:"That has its limitations.",mod:"m1"},
{id:"b2_039",de:"der Widerspruch",target:"the contradiction",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Das ist ein Widerspruch.",example_target:"That is a contradiction.",mod:"m1"},
{id:"b2_040",de:"die Ueberzeugung",target:"the conviction",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Er handelt aus Ueberzeugung.",example_target:"He acts out of conviction.",mod:"m1"},
{id:"b2_041",de:"der Rueckschluss",target:"the inference",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Was ist dein Rueckschluss?",example_target:"What is your inference?",mod:"m1"},
{id:"b2_042",de:"das Ausmass",target:"the extent",lv:"B2",tp:"Nomen",ty:"noun",example_de:"In welchem Ausmass?",example_target:"To what extent?",mod:"m1"},
{id:"b2_043",de:"der Aspekt",target:"the aspect",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Das ist ein wichtiger Aspekt.",example_target:"That is an important aspect.",mod:"m1"},
{id:"b2_044",de:"der Standpunkt",target:"the viewpoint",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Von meinem Standpunkt aus.",example_target:"From my viewpoint.",mod:"m1"},
{id:"b2_045",de:"die Tendenz",target:"the tendency",lv:"B2",tp:"Nomen",ty:"noun",example_de:"Es gibt eine Tendenz dazu.",example_target:"There is a tendency towards that.",mod:"m1"},
{id:"b2_046",de:"weitreichend",target:"far-reaching",lv:"B2",tp:"Adj",ty:"adj",example_de:"Das hat weitreichende Folgen.",example_target:"That has far-reaching consequences.",mod:"m1"},
{id:"b2_047",de:"ausschlaggebend",target:"decisive",lv:"B2",tp:"Adj",ty:"adj",example_de:"Das war ausschlaggebend.",example_target:"That was decisive.",mod:"m1"},
{id:"b2_048",de:"umstritten",target:"controversial",lv:"B2",tp:"Adj",ty:"adj",example_de:"Das ist ein umstrittenes Thema.",example_target:"That is a controversial topic.",mod:"m1"},
{id:"b2_049",de:"grundlegend",target:"fundamental",lv:"B2",tp:"Adj",ty:"adj",example_de:"Das ist ein grundlegendes Problem.",example_target:"That is a fundamental problem.",mod:"m1"},
{id:"b2_050",de:"tiefgreifend",target:"profound",lv:"B2",tp:"Adj",ty:"adj",example_de:"Eine tiefgreifende Veraenderung.",example_target:"A profound change.",mod:"m1"},
{id:"b2_051",de:"unweigerlich",target:"inevitably",lv:"B2",tp:"Adv",ty:"adv",example_de:"Das fuehrt unweigerlich dazu.",example_target:"That inevitably leads to it.",mod:"m1"},
{id:"b2_052",de:"keineswegs",target:"by no means",lv:"B2",tp:"Adv",ty:"adv",example_de:"Das ist keineswegs sicher.",example_target:"That is by no means certain.",mod:"m1"},
{id:"b2_053",de:"ausdruecklich",target:"explicitly",lv:"B2",tp:"Adv",ty:"adv",example_de:"Er hat es ausdruecklich verboten.",example_target:"He explicitly forbade it.",mod:"m1"},
{id:"b2_054",de:"im Grossen und Ganzen",target:"on the whole",lv:"B2",tp:"Adv",ty:"adv",example_de:"Im Grossen und Ganzen war es gut.",example_target:"On the whole, it was good.",mod:"m1"},
{id:"b2_055",de:"folgerichtig",target:"consequently",lv:"B2",tp:"Adv",ty:"adv",example_de:"Folgerichtig zog er Konsequenzen.",example_target:"Consequently, he drew conclusions.",mod:"m1"}
];
