// vocab/en_c1_p1.js
// C1 Phase 1 - Nuancen & abstrakte Konzepte (60 Woerter)
window.VOCAB_C1_P1 = [
{id:"c1p1_001",de:"einraeumen",target:"to concede",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er raeumte seinen Fehler ein.",example_target:"He conceded his mistake.",mod:"m5"},
{id:"c1p1_002",de:"hinterfragen",target:"to scrutinise",lv:"C1",tp:"Verben",ty:"verb",example_de:"Man sollte das hinterfragen.",example_target:"One should scrutinise that.",mod:"m5"},
{id:"c1p1_003",de:"verharmlosen",target:"to trivialise",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das darf man nicht verharmlosen.",example_target:"One must not trivialise that.",mod:"m5"},
{id:"c1p1_004",de:"bewaeltigen",target:"to overcome",lv:"C1",tp:"Verben",ty:"verb",example_de:"Sie bewaeltigte die Herausforderung.",example_target:"She overcame the challenge.",mod:"m5"},
{id:"c1p1_005",de:"praegen",target:"to shape",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das hat seine Persoenlichkeit gepraegt.",example_target:"That shaped his personality.",mod:"m5"},
{id:"c1p1_006",de:"verschaerfen",target:"to exacerbate",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das verschaerft das Problem.",example_target:"That exacerbates the problem.",mod:"m5"},
{id:"c1p1_007",de:"widerspiegeln",target:"to reflect",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das spiegelt die Realitaet wider.",example_target:"That reflects reality.",mod:"m5"},
{id:"c1p1_008",de:"abfedern",target:"to mitigate",lv:"C1",tp:"Verben",ty:"verb",example_de:"Die Auswirkungen wurden abgefedert.",example_target:"The effects were mitigated.",mod:"m5"},
{id:"c1p1_009",de:"einbetten",target:"to embed",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das ist tief eingebettet.",example_target:"That is deeply embedded.",mod:"m5"},
{id:"c1p1_010",de:"zuspitzen",target:"to come to a head",lv:"C1",tp:"Verben",ty:"verb",example_de:"Die Lage spitzt sich zu.",example_target:"The situation is coming to a head.",mod:"m5"},
{id:"c1p1_011",de:"entfalten",target:"to unfold",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das Potenzial entfaltet sich.",example_target:"The potential is unfolding.",mod:"m5"},
{id:"c1p1_012",de:"anknuepfen an",target:"to build on",lv:"C1",tp:"Verben",ty:"verb",example_de:"Wir knuepfen an frueheren Ergebnissen an.",example_target:"We build on earlier results.",mod:"m5"},
{id:"c1p1_013",de:"anmahnen",target:"to call for",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er mahnte mehr Transparenz an.",example_target:"He called for more transparency.",mod:"m5"},
{id:"c1p1_014",de:"durchdringen",target:"to permeate",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das Thema durchdringt alles.",example_target:"The topic permeates everything.",mod:"m5"},
{id:"c1p1_015",de:"die Ambivalenz",target:"the ambivalence",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Er empfindet eine gewisse Ambivalenz.",example_target:"He feels a certain ambivalence.",mod:"m5"},
{id:"c1p1_016",de:"das Paradoxon",target:"the paradox",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist ein interessantes Paradoxon.",example_target:"That is an interesting paradox.",mod:"m5"},
{id:"c1p1_017",de:"die Nuance",target:"the nuance",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das erfordert ein Gespuer fuer Nuancen.",example_target:"That requires a feel for nuance.",mod:"m5"},
{id:"c1p1_018",de:"das Dilemma",target:"the dilemma",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Wir stehen vor einem echten Dilemma.",example_target:"We face a genuine dilemma.",mod:"m5"},
{id:"c1p1_019",de:"die Praemisse",target:"the premise",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Praemisse ist fragwuerdig.",example_target:"The premise is questionable.",mod:"m5"},
{id:"c1p1_020",de:"der Konsens",target:"the consensus",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Es besteht ein breiter Konsens.",example_target:"There is a broad consensus.",mod:"m5"},
{id:"c1p1_021",de:"die Diskrepanz",target:"the discrepancy",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Es gibt eine deutliche Diskrepanz.",example_target:"There is a clear discrepancy.",mod:"m5"},
{id:"c1p1_022",de:"der Paradigmenwechsel",target:"the paradigm shift",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist ein echter Paradigmenwechsel.",example_target:"That is a genuine paradigm shift.",mod:"m5"},
{id:"c1p1_023",de:"die Abwaegung",target:"the trade-off",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist eine schwierige Abwaegung.",example_target:"That is a difficult trade-off.",mod:"m5"},
{id:"c1p1_024",de:"der Vorbehalt",target:"the caveat",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Ich habe einige Vorbehalte.",example_target:"I have some reservations.",mod:"m5"},
{id:"c1p1_025",de:"die Verflechtung",target:"the interconnection",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Verflechtungen sind komplex.",example_target:"The interconnections are complex.",mod:"m5"},
{id:"c1p1_026",de:"die Stringenz",target:"the rigour",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Argumentation braucht mehr Stringenz.",example_target:"The argument needs more rigour.",mod:"m5"},
{id:"c1p1_027",de:"die Implikation",target:"the implication",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Welche Implikationen hat das?",example_target:"What are the implications of that?",mod:"m5"},
{id:"c1p1_028",de:"bahnbrechend",target:"pioneering",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das war eine bahnbrechende Entdeckung.",example_target:"That was a pioneering discovery.",mod:"m5"},
{id:"c1p1_029",de:"wegweisend",target:"groundbreaking",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist eine wegweisende Entscheidung.",example_target:"That is a groundbreaking decision.",mod:"m5"},
{id:"c1p1_030",de:"fadenscheinig",target:"flimsy",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist ein fadenscheiniges Argument.",example_target:"That is a flimsy argument.",mod:"m5"},
{id:"c1p1_031",de:"wagemuetig",target:"audacious",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das war eine wagemuetige Entscheidung.",example_target:"That was an audacious decision.",mod:"m5"},
{id:"c1p1_032",de:"einschlaegig",target:"pertinent",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist einschlaegige Erfahrung.",example_target:"That is pertinent experience.",mod:"m5"},
{id:"c1p1_033",de:"zwiespaeltig",target:"ambivalent",lv:"C1",tp:"Adj",ty:"adj",example_de:"Ich bin zwiespaeltig.",example_target:"I feel ambivalent.",mod:"m5"},
{id:"c1p1_034",de:"unbestreitbar",target:"undeniable",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist unbestreitbar richtig.",example_target:"That is undeniably correct.",mod:"m5"},
{id:"c1p1_035",de:"stringent",target:"rigorous",lv:"C1",tp:"Adj",ty:"adj",example_de:"Die Analyse ist sehr stringent.",example_target:"The analysis is very rigorous.",mod:"m5"},
{id:"c1p1_036",de:"im Nachhinein",target:"in hindsight",lv:"C1",tp:"Adv",ty:"adv",example_de:"Im Nachhinein war das falsch.",example_target:"In hindsight that was wrong.",mod:"m5"},
{id:"c1p1_037",de:"nichtsdestotrotz",target:"nonetheless",lv:"C1",tp:"Adv",ty:"adv",example_de:"Nichtsdestotrotz hat er recht.",example_target:"Nonetheless he is right.",mod:"m5"},
{id:"c1p1_038",de:"bezeichnenderweise",target:"tellingly",lv:"C1",tp:"Adv",ty:"adv",example_de:"Bezeichnenderweise hat er geschwiegen.",example_target:"Tellingly, he remained silent.",mod:"m5"},
{id:"c1p1_039",de:"allem Anschein nach",target:"apparently",lv:"C1",tp:"Adv",ty:"adv",example_de:"Allem Anschein nach hat er recht.",example_target:"Apparently he is right.",mod:"m5"},
{id:"c1p1_040",de:"zu Recht",target:"rightly",lv:"C1",tp:"Adv",ty:"adv",example_de:"Er kritisiert das zu Recht.",example_target:"He rightly criticises that.",mod:"m5"},
{id:"c1p1_041",de:"nach wie vor",target:"still",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das ist nach wie vor relevant.",example_target:"That is still relevant.",mod:"m5"},
{id:"c1p1_042",de:"unter Umstaenden",target:"under certain circumstances",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das koennte unter Umstaenden klappen.",example_target:"That could work under certain circumstances.",mod:"m5"},
{id:"c1p1_043",de:"auf den Punkt gebracht",target:"in a nutshell",lv:"C1",tp:"Idiome",ty:"adv",example_de:"Auf den Punkt gebracht: Nein.",example_target:"In a nutshell: No.",mod:"m5"},
{id:"c1p1_044",de:"mit Blick auf",target:"with a view to",lv:"C1",tp:"Idiome",ty:"adv",example_de:"Mit Blick auf die Zukunft.",example_target:"With a view to the future.",mod:"m5"},
{id:"c1p1_045",de:"den Ausschlag geben",target:"to tip the balance",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das gab letztlich den Ausschlag.",example_target:"That ultimately tipped the balance.",mod:"m5"},
{id:"c1p1_046",de:"ins Gewicht fallen",target:"to carry weight",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das faellt kaum ins Gewicht.",example_target:"That hardly carries any weight.",mod:"m5"},
{id:"c1p1_047",de:"auf der Hand liegen",target:"to be self-evident",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das liegt doch auf der Hand.",example_target:"That is self-evident.",mod:"m5"},
{id:"c1p1_048",de:"ausser Frage stehen",target:"to be beyond question",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das steht ausser Frage.",example_target:"That is beyond question.",mod:"m5"},
{id:"c1p1_049",de:"in Einklang bringen",target:"to reconcile",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Beides laesst sich schwer in Einklang bringen.",example_target:"Both are hard to reconcile.",mod:"m5"},
{id:"c1p1_050",de:"zur Debatte stehen",target:"to be up for debate",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das steht zur Debatte.",example_target:"That is up for debate.",mod:"m5"},
{id:"c1p1_051",de:"den Rahmen sprengen",target:"to go beyond the scope",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Das wuerde den Rahmen sprengen.",example_target:"That would go beyond the scope.",mod:"m5"},
{id:"c1p1_052",de:"zum Tragen kommen",target:"to come into play",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Hier kommt Erfahrung zum Tragen.",example_target:"Experience comes into play here.",mod:"m5"},
{id:"c1p1_053",de:"Rechenschaft ablegen",target:"to be accountable",lv:"C1",tp:"Idiome",ty:"verb",example_de:"Er muss Rechenschaft ablegen.",example_target:"He must be accountable.",mod:"m5"},
{id:"c1p1_054",de:"im Grossen und Ganzen",target:"on the whole",lv:"C1",tp:"Adv",ty:"adv",example_de:"Im Grossen und Ganzen war es gut.",example_target:"On the whole it was good.",mod:"m5"},
{id:"c1p1_055",de:"aufsehenerregend",target:"sensational",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das war aufsehenerregend.",example_target:"That was sensational.",mod:"m5"},
{id:"c1p1_056",de:"der Anachronismus",target:"the anachronism",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist ein regelrechter Anachronismus.",example_target:"That is a real anachronism.",mod:"m5"},
{id:"c1p1_057",de:"die Ambiguitaet",target:"the ambiguity",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Ambiguitaet ist beabsichtigt.",example_target:"The ambiguity is intentional.",mod:"m5"},
{id:"c1p1_058",de:"auf Anhieb",target:"straight away",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das hat er auf Anhieb verstanden.",example_target:"He understood that straight away.",mod:"m5"},
{id:"c1p1_059",de:"es fehlt an Stringenz",target:"it lacks rigour",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Es fehlt an Stringenz.",example_target:"It lacks rigour.",mod:"m5"},
{id:"c1p1_060",de:"nicht zuletzt",target:"not least",lv:"C1",tp:"Adv",ty:"adv",example_de:"Nicht zuletzt wegen seiner Erfahrung.",example_target:"Not least because of his experience.",mod:"m5"}
];
