// vocab/en_c1_p3.js
// C1 Phase 3 - Gehobene Sprache & Praezision (60 Woerter)
window.VOCAB_C1_P3 = [
{id:"c1p3_001",de:"anprangern",target:"to denounce",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er prangerte die Ungerechtigkeit an.",example_target:"He denounced the injustice.",mod:"m7"},
{id:"c1p3_002",de:"beschwichtigen",target:"to appease",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er versuchte sie zu beschwichtigen.",example_target:"He tried to appease her.",mod:"m7"},
{id:"c1p3_003",de:"erzwingen",target:"to enforce",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das kann man nicht erzwingen.",example_target:"That cannot be enforced.",mod:"m7"},
{id:"c1p3_004",de:"erschuettern",target:"to shatter",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das hat sein Weltbild erschuettert.",example_target:"That shattered his worldview.",mod:"m7"},
{id:"c1p3_005",de:"beanspruchen",target:"to claim",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er beansprucht das fuer sich.",example_target:"He claims that for himself.",mod:"m7"},
{id:"c1p3_006",de:"aushebeln",target:"to undermine",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das hebelt das System aus.",example_target:"That undermines the system.",mod:"m7"},
{id:"c1p3_007",de:"verdraengen",target:"to displace",lv:"C1",tp:"Verben",ty:"verb",example_de:"Angst verdraengt die Vernunft.",example_target:"Fear displaces reason.",mod:"m7"},
{id:"c1p3_008",de:"erschliessen",target:"to open up",lv:"C1",tp:"Verben",ty:"verb",example_de:"Neue Maerkte erschliessen.",example_target:"To open up new markets.",mod:"m7"},
{id:"c1p3_009",de:"in den Schatten stellen",target:"to overshadow",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das stellt alles andere in den Schatten.",example_target:"That overshadows everything else.",mod:"m7"},
{id:"c1p3_010",de:"gleichsetzen mit",target:"to equate with",lv:"C1",tp:"Verben",ty:"verb",example_de:"Man darf das nicht gleichsetzen.",example_target:"One must not equate those.",mod:"m7"},
{id:"c1p3_011",de:"vereinnahmen",target:"to co-opt",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das Thema wird vereinnahmt.",example_target:"The topic is being co-opted.",mod:"m7"},
{id:"c1p3_012",de:"entgegenhalten",target:"to counter",lv:"C1",tp:"Verben",ty:"verb",example_de:"Dem haelt er entgegen, dass...",example_target:"He counters that...",mod:"m7"},
{id:"c1p3_013",de:"abwiegeln",target:"to play down",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er versuchte abzuwiegeln.",example_target:"He tried to play it down.",mod:"m7"},
{id:"c1p3_014",de:"ansinnen",target:"to demand",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das kann man ihm nicht ansinnen.",example_target:"One cannot demand that of him.",mod:"m7"},
{id:"c1p3_015",de:"die Zwickmuehle",target:"the catch-22",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist eine echte Zwickmuehle.",example_target:"That is a real catch-22.",mod:"m7"},
{id:"c1p3_016",de:"der Trugschluss",target:"the fallacy",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist ein Trugschluss.",example_target:"That is a fallacy.",mod:"m7"},
{id:"c1p3_017",de:"das Zerrbild",target:"the distorted picture",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das zeichnet ein Zerrbild.",example_target:"That paints a distorted picture.",mod:"m7"},
{id:"c1p3_018",de:"die Gratwanderung",target:"the balancing act",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist eine echte Gratwanderung.",example_target:"That is a real balancing act.",mod:"m7"},
{id:"c1p3_019",de:"der Knackpunkt",target:"the crux",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist der eigentliche Knackpunkt.",example_target:"That is the real crux.",mod:"m7"},
{id:"c1p3_020",de:"die Schluessigkeit",target:"the coherence",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Schluessigkeit des Arguments.",example_target:"The coherence of the argument.",mod:"m7"},
{id:"c1p3_021",de:"die Spannbreite",target:"the range",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Die Spannbreite ist enorm.",example_target:"The range is enormous.",mod:"m7"},
{id:"c1p3_022",de:"der Erkenntnisgewinn",target:"the insight gained",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Der Erkenntnisgewinn ist gross.",example_target:"The insight gained is significant.",mod:"m7"},
{id:"c1p3_023",de:"die Weichenstellung",target:"the pivotal decision",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das war eine wichtige Weichenstellung.",example_target:"That was a pivotal decision.",mod:"m7"},
{id:"c1p3_024",de:"der Sachverhalt",target:"the facts of the matter",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Wie stellt sich der Sachverhalt dar?",example_target:"What are the facts of the matter?",mod:"m7"},
{id:"c1p3_025",de:"der Gesichtspunkt",target:"the viewpoint",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Unter diesem Gesichtspunkt...",example_target:"From this viewpoint...",mod:"m7"},
{id:"c1p3_026",de:"der Stolperstein",target:"the stumbling block",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist der groesste Stolperstein.",example_target:"That is the biggest stumbling block.",mod:"m7"},
{id:"c1p3_027",de:"brisant",target:"explosive",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist ein brisantes Thema.",example_target:"That is an explosive topic.",mod:"m7"},
{id:"c1p3_028",de:"anfechtbar",target:"disputable",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist anfechtbar.",example_target:"That is disputable.",mod:"m7"},
{id:"c1p3_029",de:"unhaltbar",target:"untenable",lv:"C1",tp:"Adj",ty:"adj",example_de:"Diese Position ist unhaltbar.",example_target:"This position is untenable.",mod:"m7"},
{id:"c1p3_030",de:"treffsicher",target:"accurate",lv:"C1",tp:"Adj",ty:"adj",example_de:"Eine treffsichere Analyse.",example_target:"An accurate analysis.",mod:"m7"},
{id:"c1p3_031",de:"weitschweifig",target:"long-winded",lv:"C1",tp:"Adj",ty:"adj",example_de:"Der Vortrag war zu weitschweifig.",example_target:"The lecture was too long-winded.",mod:"m7"},
{id:"c1p3_032",de:"praegnant",target:"concise",lv:"C1",tp:"Adj",ty:"adj",example_de:"Eine praegnante Zusammenfassung.",example_target:"A concise summary.",mod:"m7"},
{id:"c1p3_033",de:"ergebnisoffen",target:"open-ended",lv:"C1",tp:"Adj",ty:"adj",example_de:"Der Prozess ist ergebnisoffen.",example_target:"The process is open-ended.",mod:"m7"},
{id:"c1p3_034",de:"nachrangig",target:"secondary",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist von nachrangiger Bedeutung.",example_target:"That is of secondary importance.",mod:"m7"},
{id:"c1p3_035",de:"vordringlich",target:"pressing",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das ist vordringlich zu loesen.",example_target:"That needs to be solved urgently.",mod:"m7"},
{id:"c1p3_036",de:"schlechthin",target:"par excellence",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das ist das Problem schlechthin.",example_target:"That is the problem par excellence.",mod:"m7"},
{id:"c1p3_037",de:"mitnichten",target:"by no means",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das stimmt mitnichten.",example_target:"That is by no means true.",mod:"m7"},
{id:"c1p3_038",de:"schwerlich",target:"hardly",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das ist schwerlich moeglich.",example_target:"That is hardly possible.",mod:"m7"},
{id:"c1p3_039",de:"wohl",target:"presumably",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das wird wohl so sein.",example_target:"That is presumably the case.",mod:"m7"},
{id:"c1p3_040",de:"nolens volens",target:"willy-nilly",lv:"C1",tp:"Adv",ty:"adv",example_de:"Er musste nolens volens zustimmen.",example_target:"He had to agree willy-nilly.",mod:"m7"},
{id:"c1p3_041",de:"dabei ist zu beachten",target:"it should be noted",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Dabei ist zu beachten, dass...",example_target:"It should be noted that...",mod:"m7"},
{id:"c1p3_042",de:"es bleibt festzuhalten",target:"it remains to be noted",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Es bleibt festzuhalten, dass...",example_target:"It remains to be noted that...",mod:"m7"},
{id:"c1p3_043",de:"das fuehrt uns zu",target:"that brings us to",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Das fuehrt uns zur Frage...",example_target:"That brings us to the question...",mod:"m7"},
{id:"c1p3_044",de:"es draengt sich die Frage auf",target:"the question arises",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Es draengt sich die Frage auf...",example_target:"The question arises whether...",mod:"m7"},
{id:"c1p3_045",de:"im Lichte dieser Erkenntnisse",target:"in light of these findings",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Im Lichte dieser Erkenntnisse...",example_target:"In light of these findings...",mod:"m7"},
{id:"c1p3_046",de:"ausgehend von",target:"starting from",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Ausgehend von dieser Annahme...",example_target:"Starting from this assumption...",mod:"m7"},
{id:"c1p3_047",de:"was nicht heisst dass",target:"which does not mean that",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Was nicht heisst, dass alles gut ist.",example_target:"Which does not mean that all is well.",mod:"m7"},
{id:"c1p3_048",de:"unter dem Strich",target:"all in all",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Unter dem Strich ist das positiv.",example_target:"All in all, that is positive.",mod:"m7"},
{id:"c1p3_049",de:"dem Grunde nach",target:"fundamentally",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Dem Grunde nach ist das korrekt.",example_target:"Fundamentally, that is correct.",mod:"m7"},
{id:"c1p3_050",de:"vorbehaltlich anderer Erkenntnisse",target:"unless other evidence emerges",lv:"C1",tp:"Phrase",ty:"phrase",example_de:"Vorbehaltlich anderer Erkenntnisse gilt...",example_target:"Unless other evidence emerges...",mod:"m7"},
{id:"c1p3_051",de:"sich auf etwas stuetzen",target:"to rely on",lv:"C1",tp:"Verben",ty:"verb",example_de:"Er stuetzt sich auf valide Daten.",example_target:"He relies on valid data.",mod:"m7"},
{id:"c1p3_052",de:"gerechtfertigt sein",target:"to be warranted",lv:"C1",tp:"Verben",ty:"verb",example_de:"Diese Kritik ist durchaus gerechtfertigt.",example_target:"This criticism is entirely warranted.",mod:"m7"},
{id:"c1p3_053",de:"hinweisen auf (akademisch)",target:"to point to",lv:"C1",tp:"Verben",ty:"verb",example_de:"Die Daten weisen klar darauf hin.",example_target:"The data clearly point to that.",mod:"m7"},
{id:"c1p3_054",de:"differenziert betrachten",target:"to view in a nuanced way",lv:"C1",tp:"Verben",ty:"verb",example_de:"Das muss man differenziert betrachten.",example_target:"That must be viewed in a nuanced way.",mod:"m7"},
{id:"c1p3_055",de:"im Lichte von",target:"in light of",lv:"C1",tp:"Adv",ty:"adv",example_de:"Im Lichte dieser Erkenntnisse ist das klar.",example_target:"In light of these findings, that is clear.",mod:"m7"},
{id:"c1p3_056",de:"das Dilemma",target:"the predicament",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Wir stecken in einem Dilemma.",example_target:"We are in a predicament.",mod:"m7"},
{id:"c1p3_057",de:"der Anachronismus (C1)",target:"the anachronism",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Das ist ein regelrechter Anachronismus.",example_target:"That is a genuine anachronism.",mod:"m7"},
{id:"c1p3_058",de:"die Einschraenkung (Vorbehalt)",target:"the caveat",lv:"C1",tp:"Nomen",ty:"noun",example_de:"Mit der Einschraenkung, dass...",example_target:"With the caveat that...",mod:"m7"},
{id:"c1p3_059",de:"aufsehenerregend",target:"causing a stir",lv:"C1",tp:"Adj",ty:"adj",example_de:"Das war ein aufsehenerregendes Urteil.",example_target:"That was a stir-causing verdict.",mod:"m7"},
{id:"c1p3_060",de:"gar",target:"at all",lv:"C1",tp:"Adv",ty:"adv",example_de:"Das ist gar nicht so einfach.",example_target:"That is not so simple at all.",mod:"m7"}
];
