// vocab/en_b2_p1.js
// B2 Phase 1 – Präpositionen & Präzise Verben (55 Wörter)
window.VOCAB_B2_P1 = [
{id:"b2_001",de:"bestehen auf",target:"to insist on",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/ɪnˈsɪst ɒn/",example_de:"Er besteht auf einer Erklärung.",example_target:"He insists on an explanation.",mod:"m1"},
{id:"b2_002",de:"sich einigen auf",target:"to agree on",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/əˈɡriː ɒn/",example_de:"Wir einigten uns auf einen Termin.",example_target:"We agreed on a date.",mod:"m1"},
{id:"b2_003",de:"abhängen von",target:"to depend on",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/dɪˈpend ɒn/",example_de:"Das hängt von dir ab.",example_target:"That depends on you.",mod:"m1"},
{id:"b2_004",de:"bestehen aus",target:"to consist of",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/kənˈsɪst ɒv/",example_de:"Das Team besteht aus fünf Personen.",example_target:"The team consists of five people.",mod:"m1"},
{id:"b2_005",de:"hinweisen auf",target:"to point out",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/pɔɪnt aʊt/",example_de:"Er wies auf den Fehler hin.",example_target:"He pointed out the mistake.",mod:"m1"},
{id:"b2_006",de:"sich kümmern um",target:"to look after",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/lʊk ˈɑːftə/",example_de:"Sie kümmert sich um die Kinder.",example_target:"She looks after the children.",mod:"m1"},
{id:"b2_007",de:"sich bewerben um",target:"to apply for",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/əˈplaɪ fɔː/",example_de:"Er bewirbt sich um die Stelle.",example_target:"He is applying for the position.",mod:"m1"},
{id:"b2_008",de:"verzichten auf",target:"to give up / do without",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/ɡɪv ʌp/",example_de:"Sie verzichtet auf Zucker.",example_target:"She does without sugar.",mod:"m1"},
{id:"b2_009",de:"ankommen auf",target:"to come down to",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/kʌm daʊn tʊ/",example_de:"Es kommt darauf an.",example_target:"It comes down to that.",mod:"m1"},
{id:"b2_010",de:"eingehen auf",target:"to respond to",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/rɪˈspɒnd tʊ/",example_de:"Er geht nicht auf die Frage ein.",example_target:"He doesn't respond to the question.",mod:"m1"},
{id:"b2_011",de:"sich verlassen auf",target:"to count on",lv:"B2",tp:"Präp",ty:"verb",phonetic:"/kaʊnt ɒn/",example_de:"Du kannst auf mich zählen.",example_target:"You can count on me.",mod:"m1"},
{id:"b2_012",de:"im Voraus",target:"in advance",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/ɪn ədˈvɑːns/",example_de:"Bitte bezahlen Sie im Voraus.",example_target:"Please pay in advance.",mod:"m1"},
{id:"b2_013",de:"angesichts",target:"in view of / given",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/ɪn vjuː ɒv/",example_de:"Angesichts der Lage ist das verständlich.",example_target:"Given the situation, that is understandable.",mod:"m1"},
{id:"b2_014",de:"im Gegensatz zu",target:"in contrast to",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/ɪn ˈkɒntrɑːst tʊ/",example_de:"Im Gegensatz zu ihm bin ich ruhig.",example_target:"In contrast to him, I am calm.",mod:"m1"},
{id:"b2_015",de:"trotz",target:"despite",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/dɪˈspaɪt/",example_de:"Trotz des Regens gingen wir spazieren.",example_target:"Despite the rain, we went for a walk.",mod:"m1"},
{id:"b2_016",de:"aufgrund von",target:"due to",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/djuː tʊ/",example_de:"Aufgrund des Staus kamen wir zu spät.",example_target:"Due to the traffic jam, we were late.",mod:"m1"},
{id:"b2_017",de:"im Hinblick auf",target:"with regard to",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/wɪð rɪˈɡɑːd tʊ/",example_de:"Im Hinblick auf die Kosten ist das günstig.",example_target:"With regard to costs, that is reasonable.",mod:"m1"},
{id:"b2_018",de:"abgesehen von",target:"apart from",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/əˈpɑːt frɒm/",example_de:"Abgesehen davon hat er recht.",example_target:"Apart from that, he is right.",mod:"m1"},
{id:"b2_019",de:"anstatt",target:"instead of",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/ɪnˈsted ɒv/",example_de:"Anstatt zu klagen, handle.",example_target:"Instead of complaining, act.",mod:"m1"},
{id:"b2_020",de:"im Zusammenhang mit",target:"in connection with",lv:"B2",tp:"Präp",ty:"adv",phonetic:"/ɪn kəˈnekʃn wɪð/",example_de:"Im Zusammenhang mit dem Projekt.",example_target:"In connection with the project.",mod:"m1"},
{id:"b2_021",de:"abwägen",target:"to weigh up",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/weɪ ʌp/",example_de:"Ich muss die Optionen abwägen.",example_target:"I need to weigh up the options.",mod:"m1"},
{id:"b2_022",de:"verdeutlichen",target:"to clarify",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈklærɪfaɪ/",example_de:"Können Sie das verdeutlichen?",example_target:"Could you clarify that?",mod:"m1"},
{id:"b2_023",de:"rechtfertigen",target:"to justify",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈdʒʌstɪfaɪ/",example_de:"Wie rechtfertigst du das?",example_target:"How do you justify that?",mod:"m1"},
{id:"b2_024",de:"widersprechen",target:"to contradict",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˌkɒntrəˈdɪkt/",example_de:"Das widerspricht sich.",example_target:"That contradicts itself.",mod:"m1"},
{id:"b2_025",de:"berücksichtigen",target:"to take into account",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/teɪk ˈɪntʊ əˈkaʊnt/",example_de:"Das sollte berücksichtigt werden.",example_target:"That should be taken into account.",mod:"m1"},
{id:"b2_026",de:"voraussetzen",target:"to presuppose",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˌpriːsəˈpəʊz/",example_de:"Das setzt Erfahrung voraus.",example_target:"That presupposes experience.",mod:"m1"},
{id:"b2_027",de:"aufwerfen",target:"to raise a question",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/reɪz/",example_de:"Das wirft Fragen auf.",example_target:"That raises questions.",mod:"m1"},
{id:"b2_028",de:"in Frage stellen",target:"to question",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈkwestʃən/",example_de:"Das sollte man in Frage stellen.",example_target:"That should be questioned.",mod:"m1"},
{id:"b2_029",de:"nachgeben",target:"to give in",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ɡɪv ɪn/",example_de:"Sie gab schließlich nach.",example_target:"She finally gave in.",mod:"m1"},
{id:"b2_030",de:"übertreffen",target:"to exceed",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ɪkˈsiːd/",example_de:"Die Ergebnisse übertrafen unsere Erwartungen.",example_target:"The results exceeded our expectations.",mod:"m1"},
{id:"b2_031",de:"einschränken",target:"to restrict",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/rɪˈstrɪkt/",example_de:"Das schränkt uns ein.",example_target:"That restricts us.",mod:"m1"},
{id:"b2_032",de:"umgehen mit",target:"to deal with",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈhændl/",example_de:"Wie gehst du damit um?",example_target:"How do you deal with that?",mod:"m1"},
{id:"b2_033",de:"hervorrufen",target:"to trigger",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈtrɪɡə/",example_de:"Was hat das hervorgerufen?",example_target:"What triggered that?",mod:"m1"},
{id:"b2_034",de:"veranschaulichen",target:"to illustrate",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ɪˈlʌstreɪt/",example_de:"Lassen Sie mich das veranschaulichen.",example_target:"Let me illustrate that.",mod:"m1"},
{id:"b2_035",de:"bekräftigen",target:"to reinforce",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˌriːɪnˈfɔːs/",example_de:"Das bekräftigt meine These.",example_target:"That reinforces my argument.",mod:"m1"},
{id:"b2_036",de:"die Schlussfolgerung",target:"the conclusion",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/kənˈkluːʒn/",example_de:"Was ist deine Schlussfolgerung?",example_target:"What is your conclusion?",mod:"m1"},
{id:"b2_037",de:"die Voraussetzung",target:"the prerequisite",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˌpriːˈrekwəzɪt/",example_de:"Das ist eine Grundvoraussetzung.",example_target:"That is a basic prerequisite.",mod:"m1"},
{id:"b2_038",de:"die Einschränkung",target:"the limitation",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˌlɪmɪˈteɪʃn/",example_de:"Das hat seine Einschränkungen.",example_target:"That has its limitations.",mod:"m1"},
{id:"b2_039",de:"der Widerspruch",target:"the contradiction",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˌkɒntrəˈdɪkʃn/",example_de:"Das ist ein Widerspruch.",example_target:"That is a contradiction.",mod:"m1"},
{id:"b2_040",de:"die Überzeugung",target:"the conviction",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/kənˈvɪkʃn/",example_de:"Er handelt aus Überzeugung.",example_target:"He acts out of conviction.",mod:"m1"},
{id:"b2_041",de:"der Rückschluss",target:"the inference",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈɪnfərəns/",example_de:"Was ist dein Rückschluss?",example_target:"What is your inference?",mod:"m1"},
{id:"b2_042",de:"das Ausmaß",target:"the extent",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ɪkˈstent/",example_de:"In welchem Ausmaß?",example_target:"To what extent?",mod:"m1"},
{id:"b2_043",de:"der Aspekt",target:"the aspect",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈæspekt/",example_de:"Das ist ein wichtiger Aspekt.",example_target:"That is an important aspect.",mod:"m1"},
{id:"b2_044",de:"der Standpunkt",target:"the viewpoint",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈvjuːpɔɪnt/",example_de:"Von meinem Standpunkt aus.",example_target:"From my viewpoint.",mod:"m1"},
{id:"b2_045",de:"die Tendenz",target:"the tendency",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈtendənsi/",example_de:"Es gibt eine Tendenz dazu.",example_target:"There is a tendency towards that.",mod:"m1"},
{id:"b2_046",de:"weitreichend",target:"far-reaching",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˈfɑːriːtʃɪŋ/",example_de:"Das hat weitreichende Folgen.",example_target:"That has far-reaching consequences.",mod:"m1"},
{id:"b2_047",de:"ausschlaggebend",target:"decisive",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/dɪˈsaɪsɪv/",example_de:"Das war ausschlaggebend.",example_target:"That was decisive.",mod:"m1"},
{id:"b2_048",de:"umstritten",target:"controversial",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˌkɒntrəˈvɜːʃl/",example_de:"Das ist ein umstrittenes Thema.",example_target:"That is a controversial topic.",mod:"m1"},
{id:"b2_049",de:"grundlegend",target:"fundamental",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˌfʌndəˈmentl/",example_de:"Das ist ein grundlegendes Problem.",example_target:"That is a fundamental problem.",mod:"m1"},
{id:"b2_050",de:"tiefgreifend",target:"profound",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/prəˈfaʊnd/",example_de:"Eine tiefgreifende Veränderung.",example_target:"A profound change.",mod:"m1"},
{id:"b2_051",de:"unweigerlich",target:"inevitably",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ɪnˈevɪtəbli/",example_de:"Das führt unweigerlich dazu.",example_target:"That inevitably leads to it.",mod:"m1"},
{id:"b2_052",de:"keineswegs",target:"by no means",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/baɪ nəʊ miːnz/",example_de:"Das ist keineswegs sicher.",example_target:"That is by no means certain.",mod:"m1"},
{id:"b2_053",de:"ausdrücklich",target:"explicitly",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ɪkˈsplɪsɪtli/",example_de:"Er hat es ausdrücklich verboten.",example_target:"He explicitly forbade it.",mod:"m1"},
{id:"b2_054",de:"im Großen und Ganzen",target:"on the whole",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ɒn ðə həʊl/",example_de:"Im Großen und Ganzen war es gut.",example_target:"On the whole, it was good.",mod:"m1"},
{id:"b2_055",de:"folgerichtig",target:"consequently",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ˈkɒnsɪkwəntli/",example_de:"Folgerichtig zog er Konsequenzen.",example_target:"Consequently, he drew conclusions.",mod:"m1"}
];
