// vocab/en_b2_p4.js
// B2 Phase 4 – Phrasal Verbs, Diskurs, Register (60 Wörter)
window.VOCAB_B2_P4 = [
{id:"b2p4_001",de:"aufgeben",target:"to give up",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/ɡɪv ʌp/",example_de:"Er hat das Rauchen aufgegeben.",example_target:"He gave up smoking.",mod:"m4"},
{id:"b2p4_002",de:"herausfinden",target:"to find out",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/faɪnd aʊt/",example_de:"Ich werde es herausfinden.",example_target:"I will find out.",mod:"m4"},
{id:"b2p4_003",de:"nachschlagen",target:"to look up",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/lʊk ʌp/",example_de:"Schlag das Wort nach.",example_target:"Look up the word.",mod:"m4"},
{id:"b2p4_004",de:"verschieben",target:"to put off",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/pʊt ɒf/",example_de:"Wir müssen das Treffen verschieben.",example_target:"We need to put off the meeting.",mod:"m4"},
{id:"b2p4_005",de:"aufholen",target:"to catch up",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/kætʃ ʌp/",example_de:"Ich muss aufholen.",example_target:"I need to catch up.",mod:"m4"},
{id:"b2p4_006",de:"aufpassen auf",target:"to look out for",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/lʊk aʊt fɔː/",example_de:"Pass auf dich auf.",example_target:"Look out for yourself.",mod:"m4"},
{id:"b2p4_007",de:"sich anmelden",target:"to sign up",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/saɪn ʌp/",example_de:"Melde dich für den Kurs an.",example_target:"Sign up for the course.",mod:"m4"},
{id:"b2p4_008",de:"eintreten für",target:"to stand up for",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/stænd ʌp fɔː/",example_de:"Steh für deine Rechte ein.",example_target:"Stand up for your rights.",mod:"m4"},
{id:"b2p4_009",de:"durchhalten",target:"to carry on",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/ˈkæri ɒn/",example_de:"Mach weiter so.",example_target:"Carry on like this.",mod:"m4"},
{id:"b2p4_010",de:"sich herausstellen",target:"to turn out",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/tɜːn aʊt/",example_de:"Es stellte sich heraus, dass…",example_target:"It turned out that…",mod:"m4"},
{id:"b2p4_011",de:"zunehmen",target:"to go up",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/ɡəʊ ʌp/",example_de:"Die Preise nehmen zu.",example_target:"Prices are going up.",mod:"m4"},
{id:"b2p4_012",de:"abnehmen",target:"to go down",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/ɡəʊ daʊn/",example_de:"Die Zahlen nehmen ab.",example_target:"The numbers are going down.",mod:"m4"},
{id:"b2p4_013",de:"überdenken",target:"to think over",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/θɪŋk ˈəʊvə/",example_de:"Denk das nochmal über.",example_target:"Think that over.",mod:"m4"},
{id:"b2p4_014",de:"zusammenbrechen",target:"to break down",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/breɪk daʊn/",example_de:"Die Verhandlungen brachen zusammen.",example_target:"The negotiations broke down.",mod:"m4"},
{id:"b2p4_015",de:"sich einigen",target:"to come to an agreement",lv:"B2",tp:"Phrasal Verb",ty:"verb",phonetic:"/kʌm tʊ ən əˈɡriːmənt/",example_de:"Wir kamen zu einer Einigung.",example_target:"We came to an agreement.",mod:"m4"},
{id:"b2p4_016",de:"andererseits",target:"on the other hand",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ɒn ðɪ ˈʌðə hænd/",example_de:"Andererseits hat er recht.",example_target:"On the other hand, he is right.",mod:"m4"},
{id:"b2p4_017",de:"abschließend",target:"in conclusion",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ɪn kənˈkluːʒn/",example_de:"Abschließend lässt sich sagen…",example_target:"In conclusion, it can be said…",mod:"m4"},
{id:"b2p4_018",de:"darüber hinaus",target:"furthermore",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ˈfɜːðəmɔː/",example_de:"Darüber hinaus ist es günstiger.",example_target:"Furthermore, it is cheaper.",mod:"m4"},
{id:"b2p4_019",de:"mit anderen Worten",target:"in other words",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ɪn ˈʌðə wɜːdz/",example_de:"Mit anderen Worten: Nein.",example_target:"In other words: No.",mod:"m4"},
{id:"b2p4_020",de:"demgegenüber",target:"in contrast",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ɪn ˈkɒntrɑːst/",example_de:"Demgegenüber steht die Tatsache.",example_target:"In contrast, there is the fact.",mod:"m4"},
{id:"b2p4_021",de:"infolgedessen",target:"as a result",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/æz ə rɪˈzʌlt/",example_de:"Infolgedessen mussten wir handeln.",example_target:"As a result, we had to act.",mod:"m4"},
{id:"b2p4_022",de:"nichtsdestoweniger",target:"nevertheless",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ˌnevəðəˈles/",example_de:"Nichtsdestoweniger versuchen wir es.",example_target:"Nevertheless, we try.",mod:"m4"},
{id:"b2p4_023",de:"insbesondere",target:"in particular",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ɪn pəˈtɪkjʊlə/",example_de:"Insbesondere gilt das für…",example_target:"In particular, this applies to…",mod:"m4"},
{id:"b2p4_024",de:"wie bereits erwähnt",target:"as mentioned",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/æz ˈmenʃənd/",example_de:"Wie bereits erwähnt, ist das wichtig.",example_target:"As mentioned, that is important.",mod:"m4"},
{id:"b2p4_025",de:"bezeichnend",target:"notably",lv:"B2",tp:"Diskurs",ty:"adv",phonetic:"/ˈnəʊtəbli/",example_de:"Bezeichnend ist dabei, dass…",example_target:"Notably, the fact is that…",mod:"m4"},
{id:"b2p4_026",de:"in Anbetracht dessen",target:"in light of this",lv:"B2",tp:"Register",ty:"adv",phonetic:"/ɪn laɪt ɒv ðɪs/",example_de:"In Anbetracht dessen schlage ich vor.",example_target:"In light of this, I suggest.",mod:"m4"},
{id:"b2p4_027",de:"es sei darauf hingewiesen",target:"it should be noted",lv:"B2",tp:"Register",ty:"phrase",phonetic:"/ɪt ʃʊd bi ˈnəʊtɪd/",example_de:"Es sei darauf hingewiesen, dass…",example_target:"It should be noted that…",mod:"m4"},
{id:"b2p4_028",de:"vorbehaltlich weiterer Prüfung",target:"subject to further review",lv:"B2",tp:"Register",ty:"adv",phonetic:"/ˈsʌbdʒɪkt tʊ ˈfɜːðə rɪˈvjuː/",example_de:"Vorbehaltlich weiterer Prüfung.",example_target:"Subject to further review.",mod:"m4"},
{id:"b2p4_029",de:"in diesem Zusammenhang",target:"in this context",lv:"B2",tp:"Register",ty:"adv",phonetic:"/ɪn ðɪs ˈkɒntekst/",example_de:"In diesem Zusammenhang ist wichtig…",example_target:"In this context, it is important…",mod:"m4"},
{id:"b2p4_030",de:"es ergibt sich daraus",target:"it follows from this",lv:"B2",tp:"Register",ty:"phrase",phonetic:"/ɪt ˈfɒləʊz frɒm ðɪs/",example_de:"Es ergibt sich daraus, dass…",example_target:"It follows from this that…",mod:"m4"},
{id:"b2p4_031",de:"unverhältnismäßig",target:"disproportionate",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˌdɪsprəˈpɔːʃənət/",example_de:"Das ist unverhältnismäßig hoch.",example_target:"That is disproportionately high.",mod:"m4"},
{id:"b2p4_032",de:"unvermeidbar",target:"inevitable",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ɪnˈevɪtəbl/",example_de:"Das ist unvermeidbar.",example_target:"That is inevitable.",mod:"m4"},
{id:"b2p4_033",de:"undurchführbar",target:"unfeasible",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ʌnˈfiːzɪbl/",example_de:"Das ist undurchführbar.",example_target:"That is unfeasible.",mod:"m4"},
{id:"b2p4_034",de:"zweideutig",target:"ambiguous",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/æmˈbɪɡjuəs/",example_de:"Die Aussage ist zweideutig.",example_target:"The statement is ambiguous.",mod:"m4"},
{id:"b2p4_035",de:"eindeutig",target:"unambiguous",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˌʌnæmˈbɪɡjuəs/",example_de:"Das ist eindeutig.",example_target:"That is unambiguous.",mod:"m4"},
{id:"b2p4_036",de:"aufwendig",target:"elaborate",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ɪˈlæbərɪt/",example_de:"Das ist sehr aufwendig.",example_target:"That is very elaborate.",mod:"m4"},
{id:"b2p4_037",de:"beträchtlich",target:"considerable",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/kənˈsɪdərəbl/",example_de:"Das ist ein beträchtlicher Aufwand.",example_target:"That is a considerable effort.",mod:"m4"},
{id:"b2p4_038",de:"maßvoll",target:"measured",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˈmeʒəd/",example_de:"Er reagierte sehr maßvoll.",example_target:"He reacted very moderately.",mod:"m4"},
{id:"b2p4_039",de:"in Kraft treten",target:"to come into effect",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/kʌm ˈɪntʊ ɪˈfekt/",example_de:"Das Gesetz tritt in Kraft.",example_target:"The law comes into effect.",mod:"m4"},
{id:"b2p4_040",de:"außer Kraft setzen",target:"to override",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˌəʊvəˈraɪd/",example_de:"Das setzt die Regel außer Kraft.",example_target:"That overrides the rule.",mod:"m4"},
{id:"b2p4_041",de:"in Angriff nehmen",target:"to tackle",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/ˈtækl/",example_de:"Wir nehmen das Problem in Angriff.",example_target:"We tackle the problem.",mod:"m4"},
{id:"b2p4_042",de:"in Kauf nehmen",target:"to accept",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/əkˈsept/",example_de:"Das nehmen wir in Kauf.",example_target:"We accept that.",mod:"m4"},
{id:"b2p4_043",de:"zur Kenntnis nehmen",target:"to take note of",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/teɪk nəʊt ɒv/",example_de:"Bitte nehmen Sie das zur Kenntnis.",example_target:"Please take note of that.",mod:"m4"},
{id:"b2p4_044",de:"in Zweifel ziehen",target:"to call into question",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/kɔːl ˈɪntʊ ˈkwestʃən/",example_de:"Das zieht seine Glaubwürdigkeit in Zweifel.",example_target:"That calls his credibility into question.",mod:"m4"},
{id:"b2p4_045",de:"zur Sprache kommen",target:"to come up",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/kʌm ʌp/",example_de:"Das Thema kam zur Sprache.",example_target:"The topic came up.",mod:"m4"},
{id:"b2p4_046",de:"aufrechterhalten",target:"to maintain",lv:"B2",tp:"Verben",ty:"verb",phonetic:"/meɪnˈteɪn/",example_de:"Das muss aufrechterhalten werden.",example_target:"That must be maintained.",mod:"m4"},
{id:"b2p4_047",de:"die Maßnahme",target:"the measure",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈmeʒə/",example_de:"Welche Maßnahmen ergreifen wir?",example_target:"What measures do we take?",mod:"m4"},
{id:"b2p4_048",de:"die Auflage",target:"the condition",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/kənˈdɪʃn/",example_de:"Unter der Auflage, dass…",example_target:"On the condition that…",mod:"m4"},
{id:"b2p4_049",de:"der Vorzug",target:"the preference",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˈprefərəns/",example_de:"Den Vorzug geben wir…",example_target:"We give preference to…",mod:"m4"},
{id:"b2p4_050",de:"die Tragfähigkeit",target:"the viability",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/ˌvaɪəˈbɪlɪti/",example_de:"Die Tragfähigkeit ist fraglich.",example_target:"The viability is questionable.",mod:"m4"},
{id:"b2p4_051",de:"der Handlungsbedarf",target:"the need for action",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/niːd fɔː ˈækʃn/",example_de:"Es besteht dringender Handlungsbedarf.",example_target:"There is an urgent need for action.",mod:"m4"},
{id:"b2p4_052",de:"der Ermessensspielraum",target:"the discretion",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/dɪˈskreʃn/",example_de:"Das liegt in Ihrem Ermessensspielraum.",example_target:"That is at your discretion.",mod:"m4"},
{id:"b2p4_053",de:"die Abhängigkeit",target:"the dependency",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/dɪˈpendənsi/",example_de:"Es besteht eine Abhängigkeit.",example_target:"There is a dependency.",mod:"m4"},
{id:"b2p4_054",de:"der Anknüpfungspunkt",target:"the point of reference",lv:"B2",tp:"Nomen",ty:"noun",phonetic:"/pɔɪnt ɒv ˈrefərəns/",example_de:"Das ist ein guter Anknüpfungspunkt.",example_target:"That is a good point of reference.",mod:"m4"},
{id:"b2p4_055",de:"naheliegend",target:"obvious",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˈɒbviəs/",example_de:"Das ist naheliegend.",example_target:"That is obvious.",mod:"m4"},
{id:"b2p4_056",de:"zweifelhaft",target:"questionable",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/ˈkwestʃənəbl/",example_de:"Das ist zweifelhaft.",example_target:"That is questionable.",mod:"m4"},
{id:"b2p4_057",de:"sinngemäß",target:"in essence",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ɪn ˈesns/",example_de:"Sinngemäß sagte er das.",example_target:"In essence, he said that.",mod:"m4"},
{id:"b2p4_058",de:"mit Ausnahme von",target:"with the exception of",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/wɪð ðɪ ɪkˈsepʃn ɒv/",example_de:"Mit Ausnahme von dir.",example_target:"With the exception of you.",mod:"m4"},
{id:"b2p4_059",de:"im Zuge von",target:"in the course of",lv:"B2",tp:"Adv",ty:"adv",phonetic:"/ɪn ðə kɔːs ɒv/",example_de:"Im Zuge der Verhandlungen.",example_target:"In the course of the negotiations.",mod:"m4"},
{id:"b2p4_060",de:"einschränkend",target:"restrictive",lv:"B2",tp:"Adj",ty:"adj",phonetic:"/rɪˈstrɪktɪv/",example_de:"Das ist eine einschränkende Regelung.",example_target:"That is a restrictive regulation.",mod:"m4"}
];
